# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the ruby-postgres driver:
#   gem install ruby-postgres
# On Mac OS X:
#   gem install ruby-postgres -- --include=/usr/local/pgsql
# On Windows:
#   gem install ruby-postgres
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
development:
  adapter: mysql
  encoding: utf8
  database: projexion
  pool: 5
  username:
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: test
  pool: 5
  username:
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: postgresql
  encoding: unicode
  database: projexion
  pool: 5
  username: rails
  password:
